import { Inter } from "next/font/google";
import "./globals.css";
import NavMob from "./components/NavMob";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-b from-[#191A19] to-black min-h-screen text-white`}
      >
        {children}
        <NavMob/>
      </body>
    </html>
  );
}
